# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appDeploymentName: accounts-deployment
appServiceName: accounts
appLabel: accounts
appName: accounts

appReplicaCount: 1

image:
  repository: sunnyrider/accounts
  tag: s14kafka

appContainerPort: 8083

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
mysqldb_enabled: true
springDataRedis_enabled: false

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083
