build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    #email: "john@eazybank.com"
    email: "{cipher}f82d3bfda6be8c122b37efbe2806b73f0fb5dad42b7145d14266255a068cf7e8553a20d52f2b462bd1af6f3bb1ce0405"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
