apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
stringData:
  password: root

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-username
type: Opaque
stringData:
  username: root

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
stringData:
  password: root
