# Default values for accountsdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mysqlDatabaseName: accountsdb
mysqlDeploymentName: accountsdb-deployment
mysqlContainerName: accountsdb-container
mysqlServiceName: accountsdb-service
mysqlPvc: accountsdb-pvc
mysqlPv: accountsdb-pv
mysqlReplicaCount: 1
mysqlContainerPort: 3306

mysqlVolumePersistentVolumeClaimStorageSize: 500Mi  #1Gi

mysqlVolumePersistentVolumeStorageSize: 500Mi  #1Gi
mysqlVolumePersistentVolumeHostPath: /var/lib/mysql  # Replace this with the actual path on your host machine

mysqlPersistentStorageName: accounts_data
mysqlVolumeMountPath: /var/lib/mysql