server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
          #search-locations: "classpath:/config"
#          search-locations: "file:///Users//frank//Documents//eazybytes"
         git:
           uri: "https://github.com/sunnyrider/eazybytes-config.git"
           default-label: main
           timeout: 5
           clone-on-start: true
           force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      eazybytes:
        configserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

encrypt:
  key: "IchMagUrinAusDerScheideVonFrauenTrinken"