server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      default-binder: kafka
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
          binder: kafka
        emailsms-out-0:
          destination: communication-sent
          binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092