# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appDeploymentName: message-deployment
appServiceName: message
appLabel: message
appName: message

appReplicaCount: 1

image:
  repository: sunnyrider/message
  tag: s14kafka

appContainerPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: true
mysqldb_enabled: false
springDataRedis_enabled: false

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010
