# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appDeploymentName: configserver-deployment
appServiceName: configserver
appLabel: configserver
appName: configserver

appReplicaCount: 1

image:
  repository: sunnyrider/configserver
  tag: s14kafka

appContainerPort: 8071

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
mysqldb_enabled: false
springDataRedis_enabled: false

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071