{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.activeProfile }}
  SPRING_CONFIG_IMPORT: {{ .Values.global.configServerURL }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.global.eurekaServerURL }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: {{ .Values.global.keyCloakURL }}
  JAVA_TOOL_OPTIONS: {{ .Values.global.openTelemetryJavaAgent }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.global.otelExporterEndPoint }}
  OTEL_METRICS_EXPORTER: {{ .Values.global.otelMetricsExporter }}
  OTEL_LOGS_EXPORTER: {{ .Values.global.otelLogsExporter }}
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: {{ .Values.global.kafkaBrokerURL }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.springDatasourceUsername }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.springDatasourcePassword }}
  MYSQL_ROOT_PASSWORD: {{ .Values.global.mysqlRootPassword }}
  SPRING_DATASOURCE_URL: {{ .Values.global.springDatasourceUrl }}
  SPRING_DATA_REDIS_CONNECT_TIMEOUT: {{ .Values.global.springDataRedisConnectTimeout }}
  SPRING_DATA_REDIS_HOST: {{ .Values.global.springDataRedisHost }}
  SPRING_DATA_REDIS_PORT: {{ .Values.global.springDataRedisPort }}
  SPRING_DATA_REDIS_TIMEOUT: {{ .Values.global.springDataRedisTimeout }}
{{- end -}}