{{- define "common.mysql-pv" -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysqlPv }}
spec:
  capacity:
    storage: {{ .Values.mysqlVolumePersistentVolumeStorageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysqlVolumePersistentVolumeHostPath }}
{{- end -}}