{{- define "common.mysql-pvc" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlPvc }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysqlVolumePersistentVolumeClaimStorageSize }}
{{- end -}}