{{- define "common.mysql-service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlServiceName }}
spec:
  selector:
    app: {{ .Values.mysqlDatabaseName }}
  ports:
      - protocol: TCP
        port: 3306
        targetPort: {{ .Values.mysqlContainerPort }}
  type: ClusterIP
{{- end -}}